export const FACILITIES = Array.from(
  new Set(
    [
      "Accepteert Relaxy bon",
      "Alcoholische dranken",
      "Anti-stressmassage",
      "Aromatherapie",
      "Aromatherapie massage",
      "Ayurvedische massage",
      "Baby massage",
      "Badjas & handdoek",
      "Badjas, slippers & handdoek",
      "Badkleding verplicht",
      "Bar",
      "Barrelsauna",
      "Betalend parkeren",
      "Bio Sauna",
      "Bubbelbad",
      "Deep tissue massage",
      "Douche faciliteiten",
      "Duo massage",
      "Eigen consumpties toegestaan",
      "Finse sauna",
      "Floating",
      "Frisdranken",
      "Fruit",
      "Gebruik van bad/doucheproducten",
      "Gebruik van haardroger",
      "Gelaatsverzorging",
      "Gratis parkeren",
      "Hamam",
      "Handdoek",
      "Hotstonemassage",
      "Hottub binnen",
      "Hottub buiten",
      "Infrarood sauna",
      "Jacuzzi binnen",
      "Jacuzzi buiten",
      "Massage",
      "Ontbijt inbegrepen",
      "Ontspanningsmassage",
      "Opgietsessies",
      "Overnachting",
      "Pedicure",
      "Privé parkeren",
      "Relaxatieruimte",
      "Rolstoel toegankelijk",
      "Sportmassage",
      "Terras",
      "Tuin",
      "Verwarmd binnenzwembad",
      "Verwarmd buitenzwembad",
      "Welkomstdrankje",
      "Wifi gebruik",
      "Zoutgrot",
      "Zwangerschapsmassage",
      "Zweedse massage",
      "Zwemvijver",
    ].map((f) => f.trim())
  )
).sort();
